schema_version = "1.0.0"
id = "auto_rig_pro"
version = "3.75.11"
name = "Auto-Rig Pro"
tagline = "Automatic rig generation based on reference bones and various tools"
maintainer = "Artell <elartblender@gmail.com>"
type = "add-on"
 website = "https://www.lucky3d.fr/auto-rig-pro/doc/"
tags = ["Rigging", "Animation"]

blender_version_min = "2.8.0"

# No upper version breakage for now
# blender_version_max = "5.1.0"

# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later", "Royalty Free", "CC0"
]
 copyright = [
   "2016-2024 Lucas Veber",
 ]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl",
# ]


# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #

[permissions]
network = "To look for updates."
files = "To save and write rig preset files on disk, export FBX, GLTF files"
clipboard = "Copy and paste bone transforms"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]