viewport_navigation_events = [
    'MIDDLEMOUSE', 'WHEELUPMOUSE', 'WHEELDOWNMOUSE',
    'TRACKPADPAN', 'TRACKPADZOOM', 'MOUSEROTATE', 'MOUSESMARTZOOM',
    'NDOF_MOTION'
]

viewport_navigation_keys = ['NUMPAD_1', 'NUMPAD_2', 'NUMPAD_3', 'NUMPAD_5', 'NUMPAD_7']

free_key = ['TAB', 'G', 'R']

fluent_modifiers_name = {
    'mirror': '.f_Mirror',
    'array_x': '.f_Array_X',
    'array_y': '.f_Array_Y',
    'array_z': '.f_Array_Z',
    'center_array_x': '.f_Move_Center_X',
    'center_array_y': '.f_Move_Center_Y',
    'center_array_z': '.f_Move_Center_Z',
    'first_solidify': '.f_First_Solidify',
    'second_solidify': '.f_Second_Solidify',
    'first_bevel': '.f_First_Bevel.',
    'second_bevel': '.f_Second_Bevel',
    'taper_x': '.f_Taper_X',
    'taper_y': '.f_Taper_Y',
    'taper_z': '.f_Taper_Z',
    'circular_displace': '.f_Circular_Displace',
    'circular_array': '.f_Circular_Array',
    'radius': '.f_Radius',
    'screw': '.f_Screw',
    'screw_2': '.f_Screw_Again',
    'decimate': '.f_Decimate',
    'curve_triangulate': '.f_Curve_Triangulate',
    'curve_subdivision': '.f_Curve_Subdiv',
    'curve_decimate': '.f_Curve_Decimate',
    'path_height': '.f_Path_Height',
    'path_displace': '.f_Path_Displace',
    'path_decimate': '.f_Path_Decimate',
    'inset_solidify': '.f_Inset_Solidify',
    'revolver_decimate': '.f_Revolver_Decimate',
    'outer_bevel': '.f_outer_bevel',
    'empty_circular': '.f_empty_circular_array',
    'scale': '.f_scale',
    'boolean': '.f_boolean',
    'weld': '.f_weld',
    'data_transfer': '.f_Data_Transfer',
    'weighted_normal': '.f_Weighted_Normal',
    'head_screw':'.f_Head_Screw'
}

fluent_stack_order = {
    'box': [
        'scale',
        'taper_x',
        'taper_y',
        'first_bevel',
        'first_solidify',
        'taper_z',
        'second_bevel',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror'
    ],
    'poly': [
        'scale',
        'curve_triangulate',
        'curve_subdivision',
        'curve_decimate',
        'taper_x',
        'taper_y',
        'first_bevel',
        'first_solidify',
        'taper_z',
        'second_bevel',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror'
    ],
    'path': [
        'path_displace',
        'scale',
        'taper_x',
        'taper_y',
        'first_bevel',
        'path_height',
        'path_decimate',
        'first_solidify',
        'taper_z',
        'second_bevel',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror'
    ],
    'prism': [
        'radius',
        'screw',
        'decimate',
        'scale',
        'taper_x',
        'taper_y',
        'first_solidify',
        'taper_z',
        'second_bevel',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror'
    ],
    'sphere': [
        'radius',
        'screw',
        'screw_2',
        'scale',
        'taper_x',
        'taper_y',
        'taper_z',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror'
    ],
    'revolver': [
        'first_bevel',
        'screw',
        'decimate',
        'scale',
        'taper_x',
        'taper_y',
        'taper_z',
        'second_bevel',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror'
    ],
    'unknow': [],
    'plate':[
        'first_solidify',
        'mirror'
    ]
}