# -*- coding: UTF-8 -*-
import bpy


def _z(phrase):
    language = bpy.context.preferences.view.language

    if language == "zh_HANS" or language == "zh_CN":
        language = "zh_CN"
    elif language == "zh_HANT" or language == "zh_TW":
        language = "zh_TW"
    else:
        language = "en_US"

    try:
        return ztranslate[language][phrase]
    except KeyError:
        # if phrase and len(phrase) > 1:
        #     print(("""%r, #%r""") % (phrase, language))
        return phrase
    except:
        print("Bug!!!@iBlender")
        return phrase


ztranslate = {
    "en_US": {
        "Language": "Language",
        "Buy More": "Buy More",
        "Chat Room": "Chat Room",
        "Language Description": "Language",
        "Watch online video tutorials": "Watch online video tutorials",
        "Translation is in progress. Whole text isn't translated": "Translation is in progress. Whole text isn't translated.",  #
        " mm": " mm",
        "A:": "A:",
        "3D View": "3D View",
        "Affects all scene cameras and their perspective guides.": "Affects all scene cameras and their perspective guides.",
        "Along X Axis": "Along X Axis",
        "Along Y Axis": "Along Y Axis",
        "Along Z Axis": "Along Z Axis",
        "Amount": "Amount",
        "Animation": "Animation",
        "Axis Display": "Axis Display",
        "Axis Point Sensitivity": "Axis Point Sensitivity",
        "Axis Point Sensitivity:": "Axis Point Sensitivity:",
        "Axis Thickness:": "Axis Thickness:",
        "Background Unmatched": "Background Unmatched",
        "Camera Distance": "Camera Distance",
        "Camera Distance: ": "Camera Distance: ",
        "Camera Offset": "Camera Offset",
        "Camera Origin": "Camera Origin",
        "Camera Rotation": "Camera Rotation",
        "Colors:": "Colors:",
        "Could not calculate grid projection for camera.": "Could not calculate grid projection for camera.",
        "Default": "Default",
        "Delete All Keyframes": "Delete All Keyframes",
        "Delete Keyframe": "Delete Keyframe",
        "Delete all Keyframes": "Delete all Keyframes",
        "Disable Control Points": "Disable Control Points",
        "Display Axis Guides": "Display Axis Guides",
        "Download fSpy": "Download fSpy",
        "Edit measuring slides": "Edit measuring slides",
        "Error calculating vanishing points.": "Error calculating vanishing points.",
        "Flatten Horizon Line": "Flatten Horizon Line",
        "Focal Length": "Focal Length",
        "Focal Length:": "Focal Length:",
        "Freeze Guides: ": "Freeze Guides: ",
        "Go to the fSpy tool website": "Go to the fSpy tool website",
        "Grid Point Color": "Grid Point Color",
        "Grid Point Color:": "Grid Point Color:",
        "Grid Point Sensitivity": "Grid Point Sensitivity",
        "Grid Point Sensitivity:": "Grid Point Sensitivity:",
        "Grid Point Size": "Grid Point Size",
        "Grid Point Size:": "Grid Point Size:",
        "Help": "Help",
        "Horizon Line Color": "Horizon Line Color",
        "Horizon Line Color:": "Horizon Line Color:",
        "Horizon Line Thickness:": "Horizon Line Thickness:",
        "Hotkey entry not found": "Hotkey entry not found",
        "Image Midpoint": "Image Midpoint",
        "Inspired by fSpy": "Inspired by fSpy",
        "Invalid Configuration": "Invalid Configuration",
        "Keyboard Shortcut:": "Keyboard Shortcut:",
        "Line Color:": "Line Color:",
        "Line Thickness:": "Line Thickness:",
        "Line thickness": "Line thickness",
        "Manual": "Manual",
        "Match Background": "Match Background",
        "Measurement Line Color": "Measurement Line Color",
        "Measurement Line Color:": "Measurement Line Color:",
        "Measurement Line Thickness:": "Measurement Line Thickness:",
        "Measuring Point A": "Measuring Point A",
        "Measuring Point B": "Measuring Point B",
        "Measuring Point Sensitivity": "Measuring Point Sensitivity",
        "Measuring Point Sensitivity:": "Measuring Point Sensitivity:",
        "Mouse Sensitivity": "Mouse Sensitivity",
        "Move Along View": "Move Along View",
        "Number of Vanishing Points": "Number of Vanishing Points",
        "P.Plotter": "P.Plotter",
        "Parameters": "Parameters",
        "Perspective Plotter Object": "Perspective Plotter Object",
        "Perspective Plotter Visualisation Object": "Perspective Plotter Visualisation Object",
        "Perspective Plotter": "Perspective Plotter",
        "Plot Perspective": "Plot Perspective",
        "Plotting...": "Plotting...",
        "Preview Line Color": "Preview Line Color",
        "Principal Point Color": "Principal Point Color",
        "Principal Point Color:": "Principal Point Color:",
        "Principal Point Sensitivity": "Principal Point Sensitivity",
        "Principal Point Sensitivity:": "Principal Point Sensitivity:",
        "Principal Point Size:": "Principal Point Size:",
        "Principal Point thickness": "Principal Point thickness",
        "Principal Point": "Principal Point",
        "Principal Point:": "Principal Point:",
        "Principal point outside vanishing points.": "Principal point outside vanishing points.",
        "Reference Distance": "Reference Distance",
        "Reference Distance:": "Reference Distance:",
        "Reference Length": "Reference Length",
        "Reference Length: ": "Reference Length: ",
        "Reset Defaults": "Reset Defaults",
        "Reset Perspective Plotter Defaults": "Reset Perspective Plotter Defaults",
        "Rotation config invalid.": "Rotation config invalid.",
        "Set Keyframe": "Set Keyframe",
        "Set to 3D Cursor": "Set to 3D Cursor",
        "Shift X:": "Shift X:",
        "Show Axis Guides:": "Show Axis Guides:",
        "Sync Camera": "Sync Camera",
        "Target Location:": "Target Location:",
        "Tools": "Tools",
        "Update Camera: ": "Update Camera: ",
        "Vanishing Point 1 Axis": "Vanishing Point 1 Axis",
        "Vanishing Point 1:": "Vanishing Point 1:",
        "Vanishing Point 2 Axis": "Vanishing Point 2 Axis",
        "Vanishing Point 2:": "Vanishing Point 2:",
        "Vanishing Points: ": "Vanishing Points: ",
        "World Center": "World Center",
        "X Axis Line Color": "X Axis Line Color",
        "X Axis Line Color:": "X Axis Line Color:",
        "Y Axis Line Color": "Y Axis Line Color",
        "Y Axis Line Color:": "Y Axis Line Color:",
        "Y:": "Y:",
        "Z Axis Line Color": "Z Axis Line Color",
        "Z Axis Line Color:": "Z Axis Line Color:",
        "fSpy is a free standalone camera matching application which can be used with other 3D tools.": "fSpy is a free standalone camera matching application which can be used with other 3D tools.",
        "restore hotkeys from Keymap tab": "restore hotkeys from Keymap tab",
    },
    "zh_CN": {
        "Language": "语言",
        "Chat Room": "加入 QQ 学习频道",
        "Buy More": "更新插件",
        "Language Description": "切换到中文界面时, 请在“编辑-偏好设置-界面-翻译”里取消勾选“新建数据”!!!",
        "Watch online video tutorials": "查看在线视频教程",
        "Translation is in progress. Whole text isn't translated": "翻译进行中, 优化纠错请联系 iBlender@taobao.com",
        "3D View": "3D 视图",
        "Affects all scene cameras and their perspective guides.": "影响所有场景相机及其透视引导",
        "Along X Axis": "沿 X 轴",
        "Along Y Axis": "沿 Y 轴",
        "Along Z Axis": "沿 Z 轴",
        "Amount": "数量",
        "Animation": "动画",
        "Axis Display": "显示轴",
        "Axis Point Sensitivity": "轴点灵敏度",
        "Axis Point Sensitivity:": "轴点灵敏度:",
        "Axis Thickness:": "轴厚度:",
        "Background Unmatched": "背景不匹配",
        "Camera Distance": "相机距离",
        "Camera Distance: ": "相机距离: ",
        "Camera Offset": "相机偏移",
        "Camera Origin": "相机原点",
        "Camera Rotation": "相机旋转",
        "Colors:": "颜色:",
        "Could not calculate grid projection for camera.": "无法计算相机的网格投影",
        "Default": "默认",
        "Delete All Keyframes": "删除所有关键帧",
        "Delete Keyframe": "删除关键帧",
        "Delete all Keyframes": "删除所有关键帧",
        "Disable Control Points": "禁用控制点",
        "Display Axis Guides": "显示轴向引导",
        "Download fSpy": "下载 fspy",
        "Edit measuring slides": "编辑测量滑动参数",
        "Error calculating vanishing points.": "计算消失点时出错",
        "Flatten Horizon Line": "展平地平线",
        "Focal Length": "焦距",
        "Focal Length:": "焦距:",
        "Freeze Guides: ": "冻结引导: ",
        "Go to the fSpy tool website": "官网免费下载, 或者花 2 文购买汉化版",
        "Grid Point Color": "栅格点颜色",
        "Grid Point Color:": "栅格点颜色:",
        "Grid Point Sensitivity": "栅格点灵敏度",
        "Grid Point Sensitivity:": "栅格点灵敏度:",
        "Grid Point Size": "栅格大小",
        "Grid Point Size:": "栅格大小:",
        "Help": "官方指南",
        "Horizon Line Color": "水平线颜色",
        "Horizon Line Color:": "水平线颜色:",
        "Horizon Line Thickness:": "水平线粗细:",
        "Hotkey entry not found": "未找到快捷键",
        "Image Midpoint": "图像中点",
        "Inspired by fSpy": "灵感来自 fSpy",
        "Invalid Configuration": "配置无效",
        "Keyboard Shortcut:": "快捷键:",
        "Line Color:": "线条颜色:",
        "Line Thickness:": "线条粗细:",
        "Line thickness": "线条粗细",
        "Manual": "手动",
        "Match Background": "匹配背景",
        "Measurement Line Color": "测量线颜色",
        "Measurement Line Color:": "测量线颜色:",
        "Measurement Line Thickness:": "测量线粗:",
        "Measuring Point A": "测量点 A",
        "Measuring Point B": "测量点 B",
        "Measuring Point Sensitivity": "测量点灵敏度",
        "Measuring Point Sensitivity:": "测量点灵敏度:",
        "Mouse Sensitivity": "鼠标灵敏度",
        "Move Along View": "沿视图移动",
        "Number of Vanishing Points": "消逝点数",
        "P.Plotter": "P.Plotter",
        "Parameters": "参数",
        "Perspective Plotter Object": "透视绘图仪对象",
        "Perspective Plotter Visualisation Object": "透视绘图仪可视化对象",
        "Perspective Plotter": "透视绘图仪",
        "Plot Perspective": "透视绘图",
        "Plotting...": "透视中...",
        "Preview Line Color": "预览线条颜色",
        "Principal Point Color": "主点颜色",
        "Principal Point Color:": "主点颜色:",
        "Principal Point Sensitivity": "主点灵敏度",
        "Principal Point Sensitivity:": "主点灵敏度:",
        "Principal Point Size:": "主点大小:",
        "Principal Point thickness": "主点厚度",
        "Principal Point": "主点",
        "Principal Point:": "主点:",
        "Principal point outside vanishing points.": "主点外消逝点",
        "Reference Distance": "参考距离",
        "Reference Distance:": "参考距离:",
        "Reference Length": "参考长度",
        "Reference Length: ": "参考长度: ",
        "Reset Defaults": "重置默认值",
        "Reset Perspective Plotter Defaults": "重置透视绘图仪默认值",
        "Rotation config invalid.": "旋转配置无效.",
        "Set Keyframe": "设置关键帧",
        "Set to 3D Cursor": "设置到 3D 游标",
        "Shift X:": "Shift X:",
        "Show Axis Guides:": "显示轴向引导:",
        "Sync Camera": "同步相机",
        "Target Location:": "目标位置:",
        "Tools": "工具",
        "Update Camera: ": "更新相机: ",
        "Vanishing Point 1 Axis": "消逝点 1 轴",
        "Vanishing Point 1:": "消逝点 1:",
        "Vanishing Point 2 Axis": "消逝点 2 轴",
        "Vanishing Point 2:": "消逝点 2:",
        "Vanishing Points: ": "消逝点: ",
        "World Center": "世界中心",
        "X Axis Line Color": "X 轴线颜色",
        "X Axis Line Color:": "X 轴线颜色:",
        "Y Axis Line Color": "Y 轴线颜色",
        "Y Axis Line Color:": "Y 轴线颜色:",
        "Z Axis Line Color": "Z 轴线颜色",
        "Z Axis Line Color:": "Z 轴线颜色:",
        "fSpy is a free standalone camera matching application which can be used with other 3D tools.": "fSpy 是免费独立相机透视程序, 可与其他 3D 工具一起使用.",
        "restore hotkeys from Keymap tab": "从 快捷键 选项卡恢复快捷键",
        "General": "常规",
        "Hide P.Plotter Panel when not in camera view.": "不在相机视图中时, 隐藏 P.Plotter 面板。",
        "Hide this Panel when not in Camera View": "不在相机视图中时, 隐藏此面板",
        "No Camera Found": "场景中无相机",
        "Switch to Camera View": "切换到相机视图",
    },
    "zh_TW": {
        "Language": "語言",
        "Chat Room": "加入 QQ 學習頻道",
        "Buy More": "更新插件",
        "Language Description": "切換到中文界面時, 請在“編輯-偏好設置-界面-翻譯”裡取消勾選“新建數據”!!!",
        "Watch online video tutorials": "查看在線視頻教程",
        "Translation is in progress. Whole text isn't translated": "翻譯進行中, 優化糾錯請聯繫 iBlender@taobao.com",
        "General": "常規",
        "Hide P.Plotter Panel when not in camera view.": "不在相機視圖中時, 隱藏 P.Plotter 面板。",
        "Hide this Panel when not in Camera View": "不在相機視圖中時, 隱藏此面板",
        "No Camera Found": "場景中無相機",
        "Switch to Camera View": "切換到相機視圖",
        "3D View": "3D 視圖",
        "Affects all scene cameras and their perspective guides.": "影響所有場景相機及其透視引導",
        "Along X Axis": "沿 X 軸",
        "Along Y Axis": "沿 Y 軸",
        "Along Z Axis": "沿 Z 軸",
        "Amount": "數量",
        "Animation": "動畫",
        "Axis Display": "顯示軸",
        "Axis Point Sensitivity": "軸點靈敏度",
        "Axis Point Sensitivity:": "軸點靈敏度:",
        "Axis Thickness:": "軸厚度:",
        "Background Unmatched": "背景不符",
        "Camera Distance": "相機距離",
        "Camera Distance: ": "相機距離: ",
        "Camera Offset": "相機偏移",
        "Camera Origin": "相機原點",
        "Camera Rotation": "相機旋轉",
        "Colors:": "顏色:",
        "Could not calculate grid projection for camera.": "無法計算相機的網格投影",
        "Default": "預設",
        "Delete All Keyframes": "刪除所有關鍵影格",
        "Delete Keyframe": "刪除關鍵影格",
        "Delete all Keyframes": "刪除所有關鍵影格",
        "Disable Control Points": "停用控制點",
        "Display Axis Guides": "顯示軸向引導",
        "Download fSpy": "下載 fspy",
        "Edit measuring slides": "編輯測量滑動參數",
        "Error calculating vanishing points.": "計算消失點時發生錯誤",
        "Flatten Horizon Line": "展平地平線",
        "Focal Length": "焦距",
        "Focal Length:": "焦距:",
        "Freeze Guides: ": "凍結引導: ",
        "Go to the fSpy tool website": "官方網站免費下載, 或花 2 文購買漢化版",
        "Grid Point Color": "柵格點顏色",
        "Grid Point Color:": "柵格點顏色:",
        "Grid Point Sensitivity": "柵格點靈敏度",
        "Grid Point Sensitivity:": "柵格點靈敏度:",
        "Grid Point Size": "柵格大小",
        "Grid Point Size:": "柵格大小:",
        "Help": "官方指南",
        "Horizon Line Color": "水平線顏色",
        "Horizon Line Color:": "水平線顏色:",
        "Horizon Line Thickness:": "水平線粗細:",
        "Hotkey entry not found": "未找到快速鍵",
        "Image Midpoint": "影像中點",
        "Inspired by fSpy": "靈感來自 fSpy",
        "Invalid Configuration": "配置無效",
        "Keyboard Shortcut:": "快速鍵:",
        "Line Color:": "線條顏色:",
        "Line Thickness:": "線條粗細:",
        "Line thickness": "線條粗細",
        "Manual": "手排",
        "Match Background": "符合背景",
        "Measurement Line Color": "測量線顏色",
        "Measurement Line Color:": "測量線顏色:",
        "Measurement Line Thickness:": "測量線粗:",
        "Measuring Point A": "測量點 A",
        "Measuring Point B": "測量點 B",
        "Measuring Point Sensitivity": "測量點靈敏度",
        "Measuring Point Sensitivity:": "測量點靈敏度:",
        "Mouse Sensitivity": "滑鼠靈敏度",
        "Move Along View": "沿視圖移動",
        "Number of Vanishing Points": "消逝點數",
        "P.Plotter": "P.Plotter",
        "Parameters": "參數",
        "Perspective Plotter Object": "透視繪圖儀物件",
        "Perspective Plotter Visualisation Object": "透視繪圖儀視覺化物件",
        "Perspective Plotter": "透視繪圖儀",
        "Plot Perspective": "透視繪圖",
        "Plotting...": "透視中...",
        "Preview Line Color": "預覽線條顏色",
        "Principal Point Color": "主點顏色",
        "Principal Point Color:": "主點顏色:",
        "Principal Point Sensitivity": "主點靈敏度",
        "Principal Point Sensitivity:": "主點靈敏度:",
        "Principal Point Size:": "主點大小:",
        "Principal Point thickness": "主點厚度",
        "Principal Point": "主點",
        "Principal Point:": "主點:",
        "Principal point outside vanishing points.": "主點外消逝點",
        "Reference Distance": "參考距離",
        "Reference Distance:": "參考距離:",
        "Reference Length": "參考長度",
        "Reference Length: ": "參考長度: ",
        "Reset Defaults": "重設預設值",
        "Reset Perspective Plotter Defaults": "重置透視繪圖儀預設值",
        "Rotation config invalid.": "旋轉配置無效.",
        "Set Keyframe": "設定關鍵影格",
        "Set to 3D Cursor": "設定到 3D 遊標",
        "Shift X:": "Shift X:",
        "Show Axis Guides:": "顯示軸向引導:",
        "Sync Camera": "同步相機",
        "Target Location:": "目標位置:",
        "Tools": "工具",
        "Update Camera: ": "更新相機: ",
        "Vanishing Point 1 Axis": "消逝點 1 軸",
        "Vanishing Point 1:": "消逝點 1:",
        "Vanishing Point 2 Axis": "消逝點 2 軸",
        "Vanishing Point 2:": "消逝點 2:",
        "Vanishing Points: ": "消逝點: ",
        "World Center": "世界中心",
        "X Axis Line Color": "X 軸線顏色",
        "X Axis Line Color:": "X 軸線顏色:",
        "Y Axis Line Color": "Y 軸線顏色",
        "Y Axis Line Color:": "Y 軸線顏色:",
        "Z Axis Line Color": "Z 軸線顏色",
        "Z Axis Line Color:": "Z 軸線顏色:",
        "fSpy is a free standalone camera matching application which can be used with other 3D tools.": "fSpy 是免費獨立相機透視程式, 可與其他 3D 工具一起使用.",
        "restore hotkeys from Keymap tab": "從 快速鍵 選項卡還原快速鍵",
    },
    "ja_JP": {
        "Language": "言語",
    },
    "fr_FR": {
        "Language": "Langue",
    },
    "de_DE": {
        "Language": "Sprache",
    },
    "ru_RU": {
        "Language": "Язык",
    },
    "ko_KR": {
        "Language": "언어",
    },
}
